#pragma once

#include <QDialog>

#include "ui_dth_exporter_gui.h"	// generated by AUTOUIC, per Qt version
#include "dth/dth_settings.h"

#include "dzapp.h"

class DthExporterGui : public QDialog, private Ui::DthExporterGui
{
	Q_OBJECT

public:

	DthExporterGui(QWidget* parent = nullptr);

private:

	DthSettings dthSettings;
	DthSettings::Settings settings;

protected slots:

	void handleCloseClicked();
	void handleBrowseClicked();
	void handleExportClicked();
	void handleExportAlembicGroomPosesClicked();
	void handleExportAnimationOnlyClicked();

};