#pragma once

#include "dznode.h"

#include "ui_dth_tools_gui.h"	// generated by AUTOUIC, per Qt version

class DazToHueToolsGui : public QWidget, private Ui::DazToHueToolsGui
{
	Q_OBJECT

public:

	DazToHueToolsGui(QWidget* parent = nullptr);

private:
	Ui::DazToHueToolsGui* ui;       // Pointer to the Qt Designer UI structure

	void populateSampleNodes();

	void addNonBoneChildrenRecursively(DzNode* dazParentNode, QTreeWidgetItem* treeParentItem);

private slots:
	// Slot hooked into twNodeVisibility->itemChanged
	void handleVisibilityToggleChanged(QTreeWidgetItem* item, int column);
	void handleDazSelectionChanged(DzNode* newSelectedNode);

protected:

protected slots:

};