#pragma once

#include "dzversion.h"

#define PLUGIN_MAJOR	2
#define PLUGIN_MINOR	1
#define PLUGIN_REV		0
#define PLUGIN_BUILD	0
#define PLUGIN_VERSION_STRING "2.1.0"
#define PLUGIN_VERSION	DZ_MAKE_VERSION( PLUGIN_MAJOR, PLUGIN_MINOR, PLUGIN_REV, PLUGIN_BUILD )
